# Generated by Django 4.2.2 on 2023-06-12 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bike',
            old_name='breed',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='bike',
            old_name='name',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='bike',
            old_name='age',
            new_name='year',
        ),
    ]
