# Generated by Django 4.2.2 on 2023-06-13 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_breed_bike_brand_rename_name_bike_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FillingDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('fuel', models.CharField(choices=[('D', 'Diesel'), ('G', 'Gasoline'), ('L', 'Gasoil')], default='D', max_length=1)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.bike')),
            ],
        ),
    ]
