# Generated by Django 4.2.2 on 2023-06-13 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_fillingdeposit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FillingDeposit',
            new_name='Filling',
        ),
    ]
