# Generated by Django 4.2.2 on 2023-06-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_toy_alter_filling_options_alter_filling_date_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='toys',
            field=models.ManyToManyField(to='main_app.toy'),
        ),
        migrations.AlterField(
            model_name='filling',
            name='date',
            field=models.DateField(verbose_name='Filling Date'),
        ),
        migrations.AlterField(
            model_name='filling',
            name='fuel',
            field=models.CharField(choices=[('G', 'Gasoline'), ('L', 'Gasoil'), ('D', 'Diesel')], default='G', max_length=1),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
